sonar.organization=arshadkhan-007
sonar.projectKey=ArshadKhan-007_URL-SHORTENER-CI-CD
sonar.projectName=URL Shortener
sonar.projectVersion=1.0

sonar.sources=app
sonar.tests=tests
sonar.language=py
sonar.sourceEncoding=UTF-8

sonar.python.coverage.reportPaths=coverage.xml

# Global exclusions across the entire workspace
sonar.exclusions=**/.env, **/.env.*, .env, .env.*, venv/**, **/__pycache__/**, tests/**
sonar.inclusions=app/**